// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Block: typeof import('./components/global-setting/block.vue')['default'];
    Breadcrumb: typeof import('./components/breadcrumb/index.vue')['default'];
    Chart: typeof import('./components/chart/index.vue')['default'];
    Footer: typeof import('./components/footer/index.vue')['default'];
    FormWrapper: typeof import('./components/global-setting/form-wrapper.vue')['default'];
    GlobalSetting: typeof import('./components/global-setting/index.vue')['default'];
    List: typeof import('./components/message-box/list.vue')['default'];
    Menu: typeof import('./components/menu/index.vue')['default'];
    MessageBox: typeof import('./components/message-box/index.vue')['default'];
    Navbar: typeof import('./components/navbar/index.vue')['default'];
    Readme: typeof import('./components/tab-bar/readme.md')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    TabBar: typeof import('./components/tab-bar/index.vue')['default'];
    TabItem: typeof import('./components/tab-bar/tab-item.vue')['default'];
  }
}
